### ISSUE TITLE
Time Duration (un)marshalling only translates to nanoseconds

### ISSUE THREAD

**Issue by oglok** [kubernetes-sigs/yaml#103]
Reading a yaml from a file (or copying config to a file) only translates to nano seconds, while the type of the param is of Time.Duration.

```
		Agent: &agentConfig{
			Server:               "https://localhost:3333",
			EnrollmentUi:         "",
			TpmPath:              "",
			FetchSpecInterval:    1 * time.Minute,
			StatusUpdateInterval: 1 * time.Minute,
		},
```

the last two params always get unmarshalled to this:

```
agent:
  fetchSpecInterval: 60000000000
  server: https://localhost:3333
  statusUpdateInterval: 60000000000
  ```

Using "gopkg.in/yaml.v3" allows to have notation such as 1m30s, while this one doesn't.

Is there any reason for that?
Thank you very much in advance.
