### ISSUE TITLE
Bug in anchor handling with UnmarshalStrict: key already set in map

### ISSUE THREAD

**Issue by jcfj** [kubernetes-sigs/yaml#46]
When trying to read this yaml file:
```yaml
arrayOfThings:
  - &shared
    name: thing-one
    attributeOne: foo
    attributeTwo: bar
  - <<: *shared
    name: thing-two
```
into these structs:
```go
type YamlToGo struct {
    ArrayOfThings []Thing `yaml:"arrayOfThings,omitempty"`
}

type Thing struct {
    Name         string `yaml:"name,omitempty"`
    AttributeOne string `yaml:"attributeOne,omitempty"`
    AttributeTwo string `yaml:"attributeTwo,omitempty"`
}
```

with `yaml.UnmarshalStrict`, the following error appears:
```
error converting YAML to JSON: yaml: unmarshal errors:
  line 8: key "name" already set in map
exit status 1
```

Thanks to @Callisto13 for creating this [reproducing example](https://github.com/Callisto13/yaml-repro).

It seems that using either the non-strict version of `Unmarshal` or `gopkg.in/yaml.v2` get around this error, but neither is really an acceptable thing to do.
