### ISSUE TITLE
Avoid hardcoding golang versions in github-actions CI, if possible

### ISSUE THREAD

**Issue by longwuyuan** [kubernetes-sigs/yaml#52]
Very softly stepping here as I dont know the head or tail of the appcode.

We are being explicit with the version of go in the github-actions ci on line 12 here https://github.com/kubernetes-sigs/yaml/edit/master/.github/workflows/go.yml ;

```
strategy:
      matrix: 
        go-versions: [1.13.x, 1.14.x, 1.15.x]
    runs-on: ubuntu-latest
```
This implies a manual task being created with each new release of golang, that the developers start using.

This issue is just to track the above mentioned change in golang releases and once for all automate the choice of go versions during CI, Alternatively we could explicitly decide to manually maintain the golang version in github-action CI, so as to maintain fine grained control on the big picture.
